### ISSUE TITLE
FlashAttention Triton broken

### ISSUE THREAD

**Issue by aska-0096** [HazyResearch/flash-attention#142]
GPU: A100-PCIE-40GB
flash-attention: dc08ea1c33afca500a3d4ada907608f7815a11d9
Triton: `triton.__version__: '2.1.0'`
Docker image Environment: nvcr.io/nvidia/pytorch:23.02-py3
### How to reproduce
1. benchmark_causal.py broken
`python benchmarks/benchmark_causal.py
`
```
FlashAttention Triton - Forward pass
Traceback (most recent call last):
  File "benchmarks/benchmark_causal.py", line 96, in <module>
    benchmark_all(flash_attn_qkvpacked_func, qkv, causal, repeats=repeats, desc='FlashAttention Triton')
  File "/usr/local/lib/python3.8/dist-packages/flash_attn-0.2.8-py3.8-linux-x86_64.egg/flash_attn/utils/benchmark.py", line 89, in benchmark_all
    benchmark_forward(fn, *inputs, repeats=repeats, desc=desc, verbose=verbose,
  File "/usr/local/lib/python3.8/dist-packages/flash_attn-0.2.8-py3.8-linux-x86_64.egg/flash_attn/utils/benchmark.py", line 17, in benchmark_forward
    fn_amp(*inputs, **kwinputs)
  File "/usr/local/lib/python3.8/dist-packages/flash_attn-0.2.8-py3.8-linux-x86_64.egg/flash_attn/utils/benchmark.py", line 15, in fn_amp
    fn(*inputs, **kwinputs)
  File "/usr/local/lib/python3.8/dist-packages/flash_attn-0.2.8-py3.8-linux-x86_64.egg/flash_attn/flash_attn_triton.py", line 728, in forward
    o, lse, ctx.softmax_scale = _flash_attn_forward(
  File "/usr/local/lib/python3.8/dist-packages/flash_attn-0.2.8-py3.8-linux-x86_64.egg/flash_attn/flash_attn_triton.py", line 594, in _flash_attn_forward
    assert bias.dtype in [q.dtype, torch.float]
AttributeError: 'bool' object has no attribute 'dtype'
```

Solved by:

- https://github.com/HazyResearch/flash-attention/blob/dc08ea1c33afca500a3d4ada907608f7815a11d9/benchmarks/benchmark_causal.py#L96 to `benchmark_all(flash_attn_qkvpacked_func, qkv, None, causal, repeats=repeats, desc='FlashAttention Triton')`
- https://github.com/HazyResearch/flash-attention/blob/dc08ea1c33afca500a3d4ada907608f7815a11d9/flash_attn/flash_attn_triton.py#L139 to `qk += tl.dot(q, tl.trans(k))`

Then second issue occured

2. FlashAttention Triton hang
```
PyTorch Attention - Forward + Backward pass
<torch.utils.benchmark.utils.common.Measurement object at 0x7fbb6c8c5460>
f(grad, *inputs, **kwinputs)
  14.25 ms
  1 measurement, 30 runs , 128 threads
FlashAttention Triton - Forward pass
^CTerminated
```
The benchmark_causal.py hang when running to triton implementation.

cc: @tridao

**Comment by tridao** [comment]
Thanks for the report.
I've just fixed the issue in `benchmark_causal.py` in the latest commit.

As mentioned in #132, this implementation was tested on triton==2.0.0.dev20221202.
Triton 2.0 has a new backend (MLIR) but seems like it doesn't yet work for head dimensions
other than [64](https://github.com/openai/triton/blob/d376020f90002757eea3ea9475d4f7cfc2ec5ead/python/triton/ops/flash_attention.py#L207). We'll update this implementation with the new Triton backend once this is fixed.

**Comment by aska-0096** [comment]
Sounds good! Looking forward to the updated implementation

**Comment by aska-0096** [comment]
The way you fix the mentioned problem in benchmark_causal.py seems caused another error.
```
Traceback (most recent call last):
  File "benchmarks/benchmark_causal.py", line 97, in <module>
    pytorch_profiler(flash_attn_qkvpacked_func, qkv, causal=causal, backward=True)
  File "/usr/local/lib/python3.8/dist-packages/flash_attn-0.2.8-py3.8-linux-x86_64.egg/flash_attn/utils/benchmark.py", line 103, in pytorch_profiler
    g = torch.randn_like(fn(*inputs, **kwinputs))
TypeError: apply() takes no keyword arguments
```
My previous solution still worked, 
`benchmark_all(flash_attn_qkvpacked_func, qkv, None, causal, repeats=repeats, desc='FlashAttention Triton')`

cc: @tridao

**Comment by tridao** [comment]
You're right, thanks for catching that.
I've pushed another commit to fix.

**Comment by aska-0096** [comment]
Hi some questions about flash-attention triton,

I did a performance test on it compared with flash-attention cuda based on triton==2.0.0.dev20221202.

I noticed that the flash-attention triton is much faster than flash attention cuda in large fixed-sequence length case, but the performance is almost same whether the causal mask set to True or False.
```
HAS_FLASH  True
HAS_FMHA_OPT  True
fmha-batch8-head12-d64-fwd:
    N_CTX  FlashAttn-CUDA  FlashAttn-Triton
0   256.0        0.045779          0.119557
1   512.0        0.096497          0.221913
2  1024.0        0.309645          0.435083
3  2048.0        1.220931          0.877189
4  4096.0        4.945163          1.761476
fmha-batch8-head12-d64-fwd_causal:
    N_CTX  FlashAttn-CUDA  FlashAttn-Triton
0   256.0        0.039961          0.127814
1   512.0        0.083571          0.237840
2  1024.0        0.224908          0.462387
3  2048.0        0.756156          0.929078
4  4096.0        2.873472          1.861905
```
Is it normal? I expect ~2x speed up when enable causal mask,
You can reproduce it with test script following:

```
import torch
import triton

from flash_attn.flash_attn_interface import flash_attn_func as flash_attn_func
from flash_attn.flash_attn_triton import flash_attn_func as ck_attn_func_triton

batch = [8]
n_heads = [12]
d_head = [64]

configs = [triton.testing.Benchmark(
    x_names=['N_CTX'],
    x_vals=[2**i for i in range(8, 13)],
    line_arg='provider',
    line_vals=['flash-cuda'] + ['flash-triton'],
    line_names=['FlashAttn-CUDA'] + ['FlashAttn-Triton'],
    styles=[('green', '-'), ('blue', '-')],
    ylabel='Time(ms)',
    plot_name=f'fmha-batch{BATCH}-head{N_HEADS}-d{D_HEAD}-{mode}',
    args={'H': N_HEADS, 'BATCH': BATCH, 'D_HEAD': D_HEAD, 'dtype': torch.float16, 'mode': mode}
) for mode in ['fwd', 'fwd_causal'] for BATCH in batch for N_HEADS in n_heads for D_HEAD in d_head]

@triton.testing.perf_report(configs)
def bench_flash_attention(BATCH, H, N_CTX, D_HEAD, mode, provider, dtype=torch.float16, device="cuda"):
    assert mode in ['fwd', 'fwd_causal']
    warmup = 25
    rep = 100

    if provider == "flash-cuda":
        lengths = torch.full((BATCH,), fill_value=N_CTX, device=device)
        cu_seqlens = torch.zeros((BATCH + 1,), device=device, dtype=torch.int32)
        cu_seqlens[1:] = lengths.cumsum(0)
        qkv = torch.randn((BATCH * N_CTX, 3, H, D_HEAD), dtype=dtype, device=device, requires_grad=True)
        if mode == 'fwd':
            fn = lambda: flash_attn_func(qkv, cu_seqlens, 0.0, N_CTX, causal=False)
        elif mode == 'fwd_causal':
            fn = lambda: flash_attn_func(qkv, cu_seqlens, 0.0, N_CTX, causal=True)

        ms = triton.testing.do_bench(fn, percentiles=None, warmup=warmup, rep=rep)
        return ms
    
    if provider == "flash-triton":
        q = torch.randn((BATCH, H, N_CTX, D_HEAD), dtype=dtype, device="cuda", requires_grad=True)
        k = torch.randn((BATCH, H, N_CTX, D_HEAD), dtype=dtype, device="cuda", requires_grad=True)
        v = torch.randn((BATCH, H, N_CTX, D_HEAD), dtype=dtype, device="cuda", requires_grad=True)
        bias = torch.randn(1, H, 1, N_CTX, dtype=torch.float, device="cuda")
        if mode == 'fwd':
            fn = lambda: ck_attn_func_triton(q, k, v, None, False)
        elif mode == 'fwd_causal':
            fn = lambda: ck_attn_func_triton(q, k, v, None, True)

        ms = triton.testing.do_bench(fn, percentiles=None, warmup=warmup, rep=rep)
        return ms

# only works on post-Ampere GPUs right now
bench_flash_attention.run(save_path='.', print_data=True)
```

cc @tridao

**Comment by tridao** [comment]
No we expect shape `(batch, seqlen, h, headdim)` not `(batch, h, seqlen, headdim)`.
You can change the shape of `q, k, v` to get the right benchmark.

As mentioned in the implementation file, currently Triton forward is generally faster than CUDA forward, while Triton backward is generally slower than CUDA backward.

**Comment by aska-0096** [comment]
Thanks for the response, let me close this issue.
