### ISSUE TITLE
The error happened in 'python setup.py install'.

### ISSUE THREAD

**Issue by zyh190507** [HazyResearch/flash-attention#182]
HI, please help me, I very like the 'flash-attention; however, I find error when I 'python setup.py install'.

No CUDA runtime is found, using CUDA_HOME='/mnt/petrelfs/share/cuda-11.6'

Warning: Torch did not find available GPUs on this system.
 If your intention is to cross-compile, this is not an error.
By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
Volta (compute capability 7.0), Turing (compute capability 7.5),
and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
If you wish to cross-compile for a single specific architecture,
export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

torch.__version__  = 1.13.1

running install
/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: v2.2.1-2-g1505ef3-master is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing flash_attn.egg-info/PKG-INFO
writing dependency_links to flash_attn.egg-info/dependency_links.txt
writing requirements to flash_attn.egg-info/requires.txt
writing top-level names to flash_attn.egg-info/top_level.txt
/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'flash_attn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cu' under directory 'flash_attn'
warning: no files found matching '*.h' under directory 'flash_attn'
warning: no files found matching '*.cuh' under directory 'flash_attn'
warning: no files found matching '*.cpp' under directory 'flash_attn'
adding license file 'LICENSE'
adding license file 'AUTHORS'
writing manifest file 'flash_attn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    setup(
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 382, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/mnt/petrelfs/zhouyunhua/miniconda3/envs/zyh_pj/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by tridao** [comment]
I haven't seen this kind of error. You can try installing `ninja` as suggested (`pip install ninja`) and then try again.

**Comment by zyh190507** [comment]
Thank you! I try right now!

**Comment by jzsbioinfo** [comment]
same problem, pip install ninja not work for me.

**Comment by YmanChris** [comment]
same problem

**Comment by mooninrain** [comment]
i encounter this problem and I found myself installing the cpu version of pytorch.
From the error traceback it seems to be a problem torch.version.cuda, which would be None for pytorch-cpu.

**Comment by YmanChris** [comment]
> same problem

I change other docker, and solved it.
