### ISSUE TITLE
Error in setup.py when installing the package from a fresh conda environment

### ISSUE THREAD

**Issue by anthonyhu** [HazyResearch/flash-attention#188]
Hello! I'm trying to install flash attention in a fresh conda environment using `pip install flash_attn==1.0.3`, but I'm getting the following error message:

```
Collecting flash_attn==1.0.3
  Using cached flash_attn-1.0.3.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a4qarcrp/flash-attn_543da69ff06f400dbac3604ba0164302/setup.py", line 6, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Do you know where this is coming from? :)

Thanks!

**Comment by huddyyeo** [comment]
I've noticed this too!

**Comment by StrangeTcy** [comment]
Did you try installing it explicitly, like `conda install -c conda-forge packaging`?

**Comment by tridao** [comment]
I suspect if you list two packages in a `requirements.txt` file, `pip` might not necessarily install them in the [order](https://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip).

**Comment by anthonyhu** [comment]
Thanks for the responses! I've created a tentative PR #193 that resolves this issue. Let me know what you think :)

**Comment by anthonyhu** [comment]
FlashAttention v2 is really impressive in terms of training speed. Thank you for that. I am still running into the same issue when installing the package 😢 . Do you think there is a way to add back the `pyproject.toml` file? (see https://github.com/Dao-AILab/flash-attention/pull/193)

**Comment by tridao** [comment]
We tried `pyproject.toml` for a while but that caused issues with some other setups regarding pytorch versions etc. I'm not experienced in package distribution, but My impression is that it's hard to specify pytorch dependency, since people could have Pytorch installed by pip or conda or their own local version.

**Comment by anasmohiuddinsyed-bit** [comment]
For setup.py/conda install errors like this in ML packages, I built **[ai-fix](https://github.com/anasmohiuddinsyed-bit/ai-fix)** — it reads your failed command and uses Claude/GPT to suggest the exact fix.

```bash
pip install ai-fix
ai-fix  # after conda/pip setup.py errors
```

~$0.0003/fix. Useful for flash-attention and other CUDA packages where build errors are environment-specific.
