### ISSUE TITLE
Problem installing package with pip 

### ISSUE THREAD

**Issue by praneetreddy017** [HazyResearch/flash-attention#204]
Hey, I have had problems installing this package using pip and stack trace is as follows. Please could I know what to do. Any help would be greatly appreciated

C:\WINDOWS\system32>pip install -U flash-attn==1.0.4 --pre
Collecting flash-attn==1.0.4
  Using cached flash_attn-1.0.4.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JkReddy\AppData\Local\Temp\pip-install-2k7m9wa0\flash-attn_0a10a14d62a84e068d2fe2dfdf51855e\setup.py", line 120, in <module>
          subprocess.run(["git", "submodule", "update", "--init", "csrc/flash_attn/cutlass"])
        File "c:\program files\python38\lib\subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "c:\program files\python38\lib\subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "c:\program files\python38\lib\subprocess.py", line 1311, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      torch.__version__  = 2.0.0+cu118

**Comment by tridao** [comment]
Duplicate of #203
