### ISSUE TITLE
Issue installing on ROCm system

### ISSUE THREAD

**Issue by KristianMischke** [HazyResearch/flash-attention#205]
Can't install on rocm system due to no `nvcc`, are there any plans to support rocm?

```sh
pip install flash-attn
Collecting flash-attn
  Downloading flash_attn-1.0.4.tar.gz (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 26.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-u_3_iwg6/flash-attn_50b8f05c9293444f90c249521d0c1819/setup.py", line 106, in <module>
          raise_if_cuda_home_none("flash_attn")
        File "/tmp/pip-install-u_3_iwg6/flash-attn_50b8f05c9293444f90c249521d0c1819/setup.py", line 53, in raise_if_cuda_home_none
          raise RuntimeError(
      RuntimeError: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.


      torch.__version__  = 1.13.1+rocm5.2


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tridao** [comment]
As mentioned in the README, we require CUDA 11.4+.
Unfortunately we have no plan to support ROCm.
