### ISSUE TITLE
IndexError about flash_attn_unpadded_qkvpacked_func

### ISSUE THREAD

**Issue by bofei5675** [HazyResearch/flash-attention#217]
I run into an Index Error when executing the following code:

```python
 from flash_attn.flash_attn_interface import flash_attn_unpadded_qkvpacked_func

output_unpad = flash_attn_unpadded_qkvpacked_func(
             a, b, c, 0.0,
             softmax_scale=None, causal=True
         )
```
variables `a,b,c` are something like
```python
a: torch.Tensor
# with torch.Size([918, 3, 40, 128]) and dtype torch.cuda.BFloat16Tensor 

b: torch.Tensor
# 1-D something like tensor([  0, 472, 918], device='cuda:6', dtype=torch.int32) 

c:int
# for example, it can be 472
```

The program throw some error like:
```
IndexError: Dimension out of range (expected to be in range of [-23456247836656, 23456247836655], but got -6148914691236517205)
```

The error message looks confusing, could anyone help?

**Comment by tridao** [comment]
I'm not able to reproduce the error, can you post a short script to reproduce the error?

```
In [1]: import torch

In [2]: from flash_attn.flash_attn_interface import flash_attn_unpadded_qkvpacked_func

In [3]: a = torch.randn(918, 3, 40, 128, dtype=torch.bfloat16, device='cuda')

In [4]: b = torch.tensor([0, 472, 918], dtype=torch.int32, device='cuda') 

In [5]: c = 472

In [6]: output_unpad = flash_attn_unpadded_qkvpacked_func( a, b, c, 0.0, softmax_scale=None, causal=True )

In [7]: output_unpad.shape
Out[7]: torch.Size([918, 40, 128])
```

**Comment by bofei5675** [comment]
I got this error for exactly same code...

e.g.

```python
import torch
from flash_attn.flash_attn_interface import flash_attn_unpadded_qkvpacked_func

a = torch.randn(918, 3, 40, 128, dtype=torch.bfloat16, device='cuda')
b = torch.tensor([0, 472, 918], dtype=torch.int32, device='cuda') 
c = 472
output_unpad = flash_attn_unpadded_qkvpacked_func( a, b, c, 0.0, softmax_scale=None, causal=True )

print(output_unpad.shape)
```

Then got exception:
```
Traceback (most recent call last):
  File "~/Projects/LLaVA/scripts/play_flash_attn.py", line 7, in <module>
    output_unpad = flash_attn_unpadded_qkvpacked_func( a, b, c, 0.0, softmax_scale=None, causal=True )
  File "~/.conda/envs/llava/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 256, in flash_attn_unpadded_qkvpacked_func
    return FlashAttnQKVPackedFunc.apply(qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale,
  File "~/.conda/envs/llava/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 58, in forward
    out, softmax_lse, rng_state, S_dmask = _flash_attn_forward(
  File "~/.conda/envs/llava/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 21, in _flash_attn_forward
    softmax_lse, rng_state, *rest = flash_attn_cuda.fwd(
IndexError: Dimension out of range (expected to be in range of [-2322221778721646699, 2322221778721646698], but got -6148914691236517205)
```

**Comment by bofei5675** [comment]
This problem has been resolved. 

I figure out that the server with A100 actually has a torch with compiled CUDA version 11.3, which is lower than flash-attn required(>11.4 I believe).

Then, I re-install pytorch nightly with CUDA 11.6 and this problem has been resolved.
(I use Pytorch nightly to use FSDP)
