### ISSUE TITLE
Flash Triton Error [CUDA]: invalid argument

### ISSUE THREAD

**Issue by cccc0der** [HazyResearch/flash-attention#245]
Hi,

I'm trying use flash attenton to speed up, flash-cuda was ok, but I got triton error when I used flash-triton with bias. 
Did it not work with T4 or any problems else?

Waiting for reply, thanks!

Also, I saw many related issues, if the bias will be integrated into flash-cuda, it should be very impressive!

```
env

NVIDIA T4
Python: 3.8.3
Cuda: 11.6
Driver Version: 510.39.01
Triton: 2.0.0.dev20221202
```

Here is my error

```
Traceback (most recent call last):
  File "pretrain_gpt.py", line 235, in <module>
    main()
  File "/home/cccc0der/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "pretrain_gpt.py", line 231, in main
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/training.py", line 189, in pretrain
    iteration = train(forward_step_func,
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/training.py", line 927, in train
    train_step(forward_step_func,
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/training.py", line 507, in train_step
    loss = model[0].train_batch(data_iter=data_iterator)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 346, in train_batch
    self._exec_schedule(sched)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 1376, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 658, in _exec_forward_pass
    outputs = super().forward(inputs)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/module.py", line 359, in forward
    x = self.activation_checkpoint_func(
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 754, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 588, in forward
    outputs = run_function(*inputs_cuda)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/module.py", line 337, in exec_func
    inputs = layer(inputs)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/model/transformer.py", line 744, in forward
    return super().forward(hidden_states, attention_mask, **kwargs)
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/model/transformer.py", line 611, in forward
    self.self_attention(layernorm_output,
  File "/home/cccc0der/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/model/transformer.py", line 468, in forward
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/model/transformer.py", line 390, in flash_attention
    matmul_result = self.flash_triton_fn(
  File "/opt/data3/cccc0der/Megatron-DeepSpeed-main-flash/megatron/model/flash_attention.py", line 14, in flash_attn_unpadded_unpacked_func_triton
    return flash_attn_triton.flash_attn_func(q, k, v, bias, causal, softmax_scale)
  File "/opt/data1/flash_attn-1.0.4/flash_attn/flash_attn_triton.py", line 810, in forward
    o, lse, ctx.softmax_scale = _flash_attn_forward(
  File "/opt/data1/flash_attn-1.0.4/flash_attn/flash_attn_triton.py", line 623, in _flash_attn_forward
    _fwd_kernel[grid](
  File "/home/cccc0der/.local/lib/python3.8/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "/home/cccc0der/.local/lib/python3.8/site-packages/triton/runtime/autotuner.py", line 200, in run
    return self.fn.run(*args, **kwargs)
  File "<string>", line 43, in _fwd_kernel
RuntimeError: Triton Error [CUDA]: invalid argument
```

**Comment by tridao** [comment]
Attention bias is only implemented in the Triton version.

**Comment by cccc0der** [comment]
> 

I have tested SparseAttention in DeepSpeed on T4 before, it is also implemented with Triton and work completely.

**Comment by cccc0der** [comment]
> Attention bias is only implemented in the Triton version. And I think this part of Triton requires at least Ampere cards (A100, RTX 3090, etc.)

I have tested SparseAttention in DeepSpeed on T4 before, it can work completely with Triton

**Comment by tridao** [comment]
> I have tested SparseAttention in DeepSpeed on T4 before, it can work completely with Triton

That code is quite different from the FlashAttention Triton code. Some Triton code works for T4, some doesn't.

**Comment by cccc0der** [comment]
> > I have tested SparseAttention in DeepSpeed on T4 before, it can work completely with Triton
> 
> That code is quite different from the FlashAttention Triton code. Some Triton code works for T4, some doesn't.

ok. get it, btw, do you have a plan to add bias-feature to flash-cuda?

**Comment by tridao** [comment]
> ok. get it, btw, do you have a plan to add bias-feature to flash-cuda?

No plan for now, but we welcome community's contribution.

**Comment by cccc0der** [comment]
> > ok. get it, btw, do you have a plan to add bias-feature to flash-cuda?
> 
> No plan for now, but we welcome community's contribution.

ok, thanks for reply :)
