### ISSUE TITLE
No Module Named 'torch'

### ISSUE THREAD

**Issue by MilesQLi** [HazyResearch/flash-attention#246]
When I run pip install flash-attn, it says that. But obviously, it is wrong. See screenshot.
![image](https://github.com/HazyResearch/flash-attention/assets/11975133/01397bac-648e-4b91-91fd-9f084aa7d7d0)

**Comment by Nicolas-M15** [comment]
Same issue for me.

**Comment by Nicolas-M15** [comment]
Workaround: install the previous version pip install flash-attn==1.0.5

**Comment by smeyerhot** [comment]
I am seeing the same problem on every `flash_attn` version. I am using Cuda 12.1 on the new g2 vm instance from gcp. https://cloud.google.com/compute/docs/accelerator-optimized-machines#g2-vms

**Comment by smeyerhot** [comment]
> Workaround: install the previous version pip install flash_attn==1.0.5

This might work in some scenarios but not all.

**Comment by tridao** [comment]
Can you try `python -m pip install flash-attn`?
It's possible that `pip` and `python -m pip` refer to different environments.

Getting the dependencies right for all setup is hard. We had `torch` in the dependency in 1.0.5, but for some users it would download a new version of torch instead of using the existing one. So for 1.0.6 we leave torch out of the dependency.

**Comment by official-elinas** [comment]
Getting the same issue. I also tried `python -m pip install flash-attn` as you suggested with the same failure.

**Comment by nrailgun** [comment]
same problem here.

**Comment by tridao** [comment]
I don't know a right solution that works for all setups, happy to hear suggestions.

We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

**Comment by smeyerhot** [comment]
I believe this is an incompatibility issue with cuda 12.1 version of torch. 

Using the following torch version solves my probem.

`torch==2.0.0+cu117`

**Comment by MilesQLi** [comment]
@smeyerhot I use the exact version, but it doesn't work. See the screenshot.

![image](https://github.com/HazyResearch/flash-attention/assets/11975133/373d9aeb-a0dc-41ce-a4c7-1a58bc0dc525)

**Comment by smeyerhot** [comment]
> I believe this is an incompatibility issue with cuda 12.1 version of torch.
> 
> Using the following torch version solves my probem.
> 
> `torch==2.0.0+cu117`

Sorry! This didn't fix things... please ignore this comment.

**Comment by MilesQLi** [comment]
@smeyerhot No problem. Thanks a lot anyway!

**Comment by jzsbioinfo** [comment]
same problem

**Comment by quant-cracker** [comment]
same problem

**Comment by leucocyte123** [comment]
`pip install flash-attn==1.0.5` might help. I am using torch 1.13 and cuda 12.0.

**Comment by Maykeye** [comment]
I had the same issue with pip. Workaround was to compile from source, worked as a charm

```python
In [1]: import flash_attn

In [2]: import torch

In [3]: torch.__version__
Out[3]: '2.0.1+cu117'

In [4]: flash_attn.__version__
Out[4]: '1.0.6'
```

**Comment by Evan-aja** [comment]
> I had the same issue with pip. Workaround was to compile from source, worked as a charm
> 
> ```python
> In [1]: import flash_attn
> 
> In [2]: import torch
> 
> In [3]: torch.__version__
> Out[3]: '2.0.1+cu117'
> 
> In [4]: flash_attn.__version__
> Out[4]: '1.0.6'
> ```

I also had the same issue, but my system needs Cuda 12.1 (2x Nvidia L4). so using torch 117 is not an option.

this is also my workaround and it works like a charm.

my system uses Fedora Server

**Comment by official-elinas** [comment]
I compiled it myself using a docker container and I still get
`RuntimeError: Expected q_dtype == torch::kFloat16 || ((is_sm8x || is_sm90) && q_dtype == torch::kBFloat16) to be true`

**Comment by xwyzsn** [comment]
try `pip install flash-attn --no-build-isolation`  fixed my problem.  
[pip docs](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation)
to fix this problem, maybe adding torch dependency into [pyproject.toml](https://github.com/HazyResearch/flash-attention/blob/main/pyproject.toml) can help

**Comment by official-elinas** [comment]
@xwyzsn Unfortunately this only worked on my windows system, not linux. But I feel we're making progress.

**Comment by tridao** [comment]
> to fix this problem, maybe adding torch dependency into [pyproject.toml](https://github.com/HazyResearch/flash-attention/blob/main/pyproject.toml) can help

We had torch in the dependency in 1.0.5, but for some users it would download a new version of torch instead of using the existing one.
I'm not really an expert in Python packaging, so it's possible I'm doing sth wrong.

**Comment by xwyzsn** [comment]
> @xwyzsn Unfortunately this only worked on my windows system, not linux. But I feel we're making progress.

Hi, actually I am using linux. It also worked well. I assume that you may missed some other package  to build this up  in your linux system. 

>  `--no-build-isolation` ...Build dependencies specified by PEP 518 must be already installed if this option is used.

**Comment by bansky-cl** [comment]
same problem to me,  i solve by check my device and torch cuda version.

**Comment by Wraken** [comment]
> try `pip install flash-attn --no-build-isolation` fixed my problem. [pip docs](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation) to fix this problem, maybe adding torch dependency into [pyproject.toml](https://github.com/HazyResearch/flash-attention/blob/main/pyproject.toml?rgh-link-date=2023-05-31T13%3A00%3A07Z) can help

This fixed the torch problem, but now I got an other error but might be related to something else.

```/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
        435 |         function(_Functor&& __f)
            |                                                                                                                                                 ^
      /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
      /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
        530 |         operator=(_Functor&& __f)
            |                                                                                                                                                  ^
      /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
      error: command '/usr/bin/nvcc' failed with exit code 255
```

**Comment by vchiley** [comment]
<img width="748" alt="Screenshot 2023-06-02 at 3 50 03 PM" src="https://github.com/HazyResearch/flash-attention/assets/6439018/c2f60eee-4007-48e8-bff3-e420c947cb4b">


@xwyzsn ninja was removed, then torch was removed, then ninja was re-added. Next logical step is to re-add torch. right??? 😄

**Comment by RuABraun** [comment]
There must be some recent change that caused this issue. @tridao

**Comment by CallShaul** [comment]
Same issue in Kubuntu 20 with torch 2.0.1 and cuda 11.8 python 3.9 / python 3.10 and flash-attn versions 0.2.8 / 1.0.4 / 1.0.5 / 1.0.6 / 1.0.7 with and without --no-build-isolation flag.

**Comment by BaohaoLiao** [comment]
Thanks to the previous answers, I can install it successfully. Here is my experience:
**Environment**
torchv2.0.0 + cuda11.7 on Ubuntu

1. I meet error as `ModuleNotFoundError: No module named 'torch'`, then I install as `pip install flash-attn --no-build-isolation`
2. It raises another error as `ModuleNotFoundError: No module named 'packaging'`, then I install this package as `pip install packaging`
3. re-run the installation, another error comes `RuntimeError: The current installed version of g++ (4.8.5) is less than the minimum required version by CUDA 11.7 (6.0.0). Please make sure to use an adequate version of g++ (>=6.0.0, <12.0).`
4. I use a higher version of g++9.0, and it finally works

**Comment by Talkvibes** [comment]
> Workaround: install the previous version pip install flash_attn==1.0.5

<img width="633" alt="image" src="https://github.com/HazyResearch/flash-attention/assets/63354721/65dec0de-af13-4b61-a2a8-4709f6016e48">
 how do tackle this

**Comment by smeyerhot** [comment]
> > I had the same issue with pip. Workaround was to compile from source, worked as a charm
> 
> > 
> 
> > ```python
> 
> > In [1]: import flash_attn
> 
> > 
> 
> > In [2]: import torch
> 
> > 
> 
> > In [3]: torch.__version__
> 
> > Out[3]: '2.0.1+cu117'
> 
> > 
> 
> > In [4]: flash_attn.__version__
> 
> > Out[4]: '1.0.6'
> 
> > ```
> 
> 
> 
> I also had the same issue, but my system needs Cuda 12.1 (2x Nvidia L4). so using torch 117 is not an option.
> 
> 
> 
> this is also my workaround and it works like a charm.
> 
> 
> 
> my system uses Fedora Server

What was your solution for cuda 12 and L4 gpu?

**Comment by Edresson** [comment]
I got the same issue here. I only was able to build from the source (clone the repo then run `python setup.py install`). `pip install git+https://github.com/HazyResearch/flash-attention` also give me the same error.

**Comment by Martion-z** [comment]
> > try `pip install flash-attn --no-build-isolation` fixed my problem. [pip docs](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation) to fix this problem, maybe adding torch dependency into [pyproject.toml](https://github.com/HazyResearch/flash-attention/blob/main/pyproject.toml?rgh-link-date=2023-05-31T13%3A00%3A07Z) can help
> 
> This fixed the torch problem, but now I got an other error. Might be related to something else tho.
> 
> ```
>         435 |         function(_Functor&& __f)
>             |                                                                                                                                                 ^
>       /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
>       /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
>         530 |         operator=(_Functor&& __f)
>             |                                                                                                                                                  ^
>       /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
>       error: command '/usr/bin/nvcc' failed with exit code 255
> ```

I had the same issue. Could you solve this?

**Comment by tridao** [comment]
@Martion-z looks the same as #172 and #225. Some version of CUDA doesn't like gcc 11. Downgrading to gcc 10 might work.

**Comment by shahules786** [comment]
```
conda install -c conda-forge cudatoolkit-dev
pip flash_attn==1.0.5
```
This woked for me.

**Comment by Crysflair** [comment]
> pip install flash-attn==1.0.5

Thanks! This solves the above error. But there's still a new one occurs: The detected CUDA version (12.1) mismatches the version that was used to compile.

**Comment by Crysflair** [comment]
> > pip install flash-attn==1.0.5
> 
> Thanks! This solves the above error. But there's still a new one occurs: The detected CUDA version (12.1) mismatches the version that was used to compile.

Problem solved. I installed the nightly version of pytorch, and then install flash-attn with the no-build-isolation option.

```
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121
# Successfully installed torch-2.1.0.dev20230710+cu121
pip install flash-attn --no-build-isolation
# Successfully built flash-attn
# Installing collected packages: ninja, flash-attn
# Successfully installed flash-attn-1.0.8 ninja-1.11.1
```
Note the wheel building process takes a long time. Don't kill it and just wait.

**Comment by Nan-Do** [comment]
There are a lot of things that can go wrong when installing this package.
Next I'm going to share a recipe that should work right now using conda. 

Some remarks:
 - Don't use pip to install any cuda or pytorch libraries 
 - Make sure you don't have several versions of CUDA installed, if that is your case the installation might fail.
 - Try to install [ninja](https://ninja-build.org/) from your distribution's package manager. The process might work without having it installed but it does a much better job detecting the environment.
  - If you couldn't install it before I strongly recommend to start from a fresh conda environment.
  - This work with the current torch version and cuda 11.8 no warranties that it will keep working for future versions.
 
Create a new environment if you don't have already one.
``` sh
conda create -n flash_attn python=3.10.11
conda activate flash_attn
```
These are the required packages with the required version.
``` sh
conda install -c conda-forge gcc=11.3
conda install -c conda-forge gxx=11.3
conda install cuda -c nvidia/label/cuda-11.8.0
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
pip install packaging
pip install flash_attn --no-build-isolation
```

**Comment by jinghan23** [comment]
> There are a lot of things that can go wrong when installing this package. Next I'm going to share a recipe that should work right now using conda.
> 
> Some remarks:
> 
> * Don't use pip to install any cuda or pytorch libraries  (this include any package that might reference them before having them installed via conda)
> * Make sure you don't have several versions of CUDA installed, if that is your case the installation might fail.
> * Try to install [ninja](https://ninja-build.org/) from your distribution's package manager. The process might work without having it installed but it does a much better job detecting the environment.
> * This work with the current torch version and cuda 11.8 no warranties that it will keep working for future versions.
> * If you couldn't install it before I strongly recommend to start from a fresh conda environment.
> 
> Create a new environment if you don't have already one.
> 
> ```shell
> conda create -n flash_attn python=3.10.11
> conda activate flash_attn
> ```
> 
> These are the required packages with their required versions.
> 
> ```shell
> conda install -c conda-forge gcc=11.3
> conda install -c conda-forge gxx=11.3
> conda install cuda -c nvidia/label/cuda-11.8.0
> conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
> pip install packaging
> pip install flash_attn --no-build-isolation
> ```

Thanks for your kind and detailed recipe! But I still meet this problem...

```
Collecting flash_attn                                                                                                                                                
  Using cached flash_attn-1.0.9.tar.gz (1.8 MB)                                                                                                                      
  Preparing metadata (setup.py) ... error                                                                                                                            
  error: subprocess-exited-with-error                                                                                                                                
                                                                                                                                                                     
  × python setup.py egg_info did not run successfully.                                                                                                               
  │ exit code: 1                                                                                                                                                     
  ╰─> [21 lines of output]                                                                                                                                           
      Traceback (most recent call last):                                                                                                                             
        File "<string>", line 2, in <module>                                                                                                                         
        File "<pip-setuptools-caller>", line 34, in <module>                                                                                                         
        File "/tmp/pip-install-57_5gf64/flash-attn_939101cdc95c431a947f582f325cfb21/setup.py", line 111, in <module>                                                 
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)                                                                                             
        File "/tmp/pip-install-57_5gf64/flash-attn_939101cdc95c431a947f582f325cfb21/setup.py", line 26, in get_cuda_bare_metal_version                               
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)                                                              
        File "/home/adseadmin/miniconda3/envs/lmtest0/lib/python3.10/subprocess.py", line 421, in check_output                                                       
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                           
        File "/home/adseadmin/miniconda3/envs/lmtest0/lib/python3.10/subprocess.py", line 503, in run                                                                
          with Popen(*popenargs, **kwargs) as process:                                                                                                               
        File "/home/adseadmin/miniconda3/envs/lmtest0/lib/python3.10/subprocess.py", line 971, in __init__                                                           
          self._execute_child(args, executable, preexec_fn, close_fds,                                                                                               
        File "/home/adseadmin/miniconda3/envs/lmtest0/lib/python3.10/subprocess.py", line 1863, in _execute_child                                                    
          raise child_exception_type(errno_num, err_msg, err_filename)                                                                                               
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda-11.5/bin/nvcc'                                                                        
                                                                                                                                                                     
                                                                                                                                                                     
      torch.__version__  = 2.0.1                                                                                                                                     
                                                                                                                                                                     
                                                                                                                                                                     
      [end of output]                                                                                                                                                
                                                                                                                                                                     
  note: This error originates from a subprocess, and is likely not a problem with pip.                                                                               
error: metadata-generation-failed                                                                                                                                    
                                                                                                                                                                     
× Encountered error while generating package metadata.                                                                                                               
╰─> See above for output.                                                                                                                                            
                                                                                                                                                                     
note: This is an issue with the package mentioned above, not pip.                                                                                                    
hint: See above for details. 
```

**Comment by Nan-Do** [comment]
@jinghan23 See point two, you have several versions of CUDA installed.

**Comment by Wraken** [comment]
The solution I've found working : 
 - Find version of cuda used by torch
 - Install the right cuda toolkit, for me it was `cuda 11.7` -> follow instruction [here ](https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=11&target_type=deb_network)
 Example :
 ```
 $ wget -d https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/cuda-keyring_1.0-1_all.deb
 $ sudo dpkg -i cuda-keyring_1.0-1_all.deb
 $ sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/3bf863cc.pub
 $ add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/ /"
 $ add-apt-repository contrib
 $ sudo apt-get update
 $ apt-get -y install cuda-11-7
 ```
 - Install `g++-10` and `gcc-10`
 - Install flash-attn like this : `CXX=g++-10 CC=gcc-10 LD=g++-10 pip3 install flash-attn==v1.0.3.post0`
 
 I've not tried on other version of flash-attn, but I think it should works too

**Comment by karandua2016** [comment]
The workaround that worked for me was to downgrade the cuda runtime version. My driver version is still 12.2 but the runtime version is now 11.7.

`conda install -c "nvidia/label/cuda-11.7.0" cuda-toolkit`

**Comment by HadiAskari** [comment]
flash-attn is a very problematic library

**Comment by xylcbd** [comment]
you **MUST** install flash-atten **after** torch been installed

**Comment by fakerybakery** [comment]
Solution: Install PyTorch first, then install FA2.

Example:

WRONG:
```
$ pip install torch flash-attn
```
CORRECT:
```
$ pip install torch
$ pip install flash-attn
```
([source](https://twitter.com/realmrfakename/status/1770888614773502195))

**Comment by phoerious** [comment]
Tried adding torch also as a build and not just a runtime dependency in my pyproject.toml. Doubled the install time, but didn't actually work.

My workaround now is to have it as an optional dependency:
```toml
[project.optional-dependencies]
# Flash attention cannot be installed alongside normal dependencies,
# since it requires torch during build time. Install with
#     pip install '.[flash-attn]'
# after installing everything else first.
flash-attn = [
    "flash-attn>=2.5.7"
]
```
And then do two pip installs. One without `[flash-attn]` and then one with `[flash-attn]`.

**Comment by cclough** [comment]
> `pip install flash-attn==1.0.5` might help. I am using torch 1.13 and cuda 12.0.

after I do this, I get this error:

`TypeError: MHA.__init__() got an unexpected keyword argument 'num_heads_kv'`

**Comment by mirekphd** [comment]
> We had torch in the dependency in 1.0.5, but for some users it would download a new version of torch instead of using the existing one. I'm not really an expert in Python packaging, so it's possible I'm doing sth wrong.

You are right that omitting in your requirements such an hard to install and popular dependency like torch is the best practice (judging from the wrappers on "classic" ML algos such as `xgboost` or `lightgbm`).

The problem here is that your installer tries to `import torch`, which is a not a good idea, because it fails if unless developers are able to guarantee your exact expected installation sequence: fist `torch` then `flash-attn`, which really is the last thing to be expected from batch installation processes or in new environments. This routinely happens in `Dockerfile`s of GPU-enabled docker containers, because there we install GPU-enabled packages such as `torch` as the last ones precisely because some of their wrappers still (despite all the educational efforts :) contain CPU-only versions as their requirements and we need to exchange CPU-only `torch` (`tensorflow`, `xgboost`, ...) for the correct GPU-enabled version.

**Comment by amirsoofi** [comment]
Make sure you're using the latest version of pip, wheel and setuptools.  Then it's fine.

`python3 -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip wheel setuptools
python -m pip install flash-attn`

**Comment by atnafuatx** [comment]
Does anyone know how we can use the flash_attn current version in T4 GPU? I am using a model that uses flash attn and I am unable to load it in the T4 machine

**Comment by ManuelSokolov** [comment]
anyone having problems with macbookpro m3?

**Comment by riturajj-cerebras** [comment]
Following sequence works:
```
python -m venv ~/myvenv
source ~/myvenv/bin/activate
pip install torch==2.3.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install wheel
pip install flash-attn --no-build-isolation
```

**Comment by koutheir** [comment]
> Following sequence works:
> 
> ```
> python -m venv ~/myvenv
> source ~/myvenv/bin/activate
> pip install torch==2.3.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> pip install wheel
> pip install flash-attn --no-build-isolation
> ```

It still fails, unfortunately:

```shell
❯ pip install flash-attn --no-build-isolation
Collecting flash-attn
  Using cached flash_attn-2.6.3.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      /tmp/pip-install-x4jog5zz/flash-attn_437d70419cfa4722bb9fe12daabe7121/setup.py:95: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-x4jog5zz/flash-attn_437d70419cfa4722bb9fe12daabe7121/setup.py", line 179, in <module>
          CUDAExtension(
        File "/home/koutheir/projects/ml-tts/venv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1077, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/koutheir/projects/ml-tts/venv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1204, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/koutheir/projects/ml-tts/venv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      
      
      torch.__version__  = 2.3.0+cu118
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jackbravo** [comment]
> anyone having problems with macbookpro m3?

@ManuelSokolov. Seeing the requirements of the README, it says that this project requires CUDA, so I don't think you can run it with an M3. But also, on the file usage.md it mentions a fork for apple silicon: https://github.com/philipturner/metal-flash-attention

**Comment by Calandiel** [comment]
The proposed solutions here are (imho) problematic. Using an nvidia container is a huge dependency and I personally find it difficult to trust a build with no isolation (to not mess up my existing setup) for a library that seems to have a messy installation process.

**Comment by albertotono** [comment]
Dear Professor @tridao and team, 

I am having the same issue with these
- flash-attn==2.5.6, 
- causal-conv1d==1.1.3.post1 
- mamba-ssm==1.1.4


![Screenshot 2024-11-08 at 3 31 46 PM](https://github.com/user-attachments/assets/af6838f3-85a8-4096-a548-3005c2c751a8)

I have torch = 2.1 and CUDA 12.2, I am following this https://github.com/kuleshov-group/mdlm 

In my case I solve add in the `.toml `directly the wheel 

- mamba-ssm = {url = "https://github.com/state-spaces/mamba/releases/download/v2.2.2/mamba_ssm-2.2.2+cu122torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl"}
- flash-attn = {url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.6/flash_attn-2.5.6+cu122torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl"}
- causal-conv1d = {url = "https://github.com/Dao-AILab/causal-conv1d/releases/download/v1.1.3.post1/causal_conv1d-1.1.3.post1+cu122torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl"}

I hope it helps for all the community.

**Comment by thesillystudent** [comment]
for me jinja was not installed. pip install jinja fixe it.

**Comment by ismael-elatifi** [comment]
> try `pip install flash-attn --no-build-isolation` fixed my problem. [pip docs](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation) to fix this problem, maybe adding torch dependency into [pyproject.toml](https://github.com/HazyResearch/flash-attention/blob/main/pyproject.toml) can help

This worked for me. I actually needed to run those 3 commands :  
```
pip install setuptools
sudo apt-get install python3-dev  # to build flash-attn
pip install flash-attn==1.0.5 --no-build-isolation
```

I have :  
- python 3.10.12
- Cuda compilation tools, release 12.6, V12.6.77
- torch 2.3.1

**Comment by him-god** [comment]
> Following sequence works:
> 
> ```
> python -m venv ~/myvenv
> source ~/myvenv/bin/activate
> pip install torch==2.3.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> pip install wheel
> pip install flash-attn --no-build-isolation
> ```

it works when I try to run LLaVA

**Comment by jnt0rrente** [comment]
Can confirm
```
pip install torch
pip install psutil //also required by flash-attn
pip install flash-attn --no-build-isolation //to be able to find the previous two packages
```
Worked for me flawlessly. Honestly this should be fixed, why would a package depend on pytorch at build time?

**Comment by metal3d** [comment]
It's actually a bit more complex for me. Needed to setup the CUDA_HOME environement and add PATH to use older gcc on Fedora...

```bash
sudo dnf install cuda
sudo dnf install gcc13

# link gcc13 to CUDA env
export CUDA_HOME=/usr/local/cuda-12.6
sudo ln -sf /usr/bin/gcc-13 $CUDA_HOME/bin
sudo ln -sf /usr/bin/g++-13 $CUDA_HOME/bin

# in my virtualenv
# necessary
export CUDA_HOME=/usr/local/cuda-12.6
export PATH=$CUDA_HOME/bin:$PATH

# and then, I can install flash-attn, use ComfyUI with damned CUDA
# I hope that CUDA will be later replaced by SYSCL, Vulkan, or OpenCL...
```

**Comment by mfoste** [comment]
On Windows. I had upgraded from CUDA 11.8 to 12.4. My issue was that CUDA_HOME env was still pointing at 11.8. Once I updated CUDA_HOME to point to 12.4, 'pip install flash-attn' succeeded.

**Comment by HiDolen** [comment]
For PDM users, I leave here a solution that worked for me (Ubuntu):

```
pdm add setuptools packaging wheel psutil 
export CUDA_HOME=/usr/local/cuda-12.5
export PATH=$CUDA_HOME/bin:$PATH
pdm add flash-attn --no-isolation
```

I'm not sure which step made the difference, but it did work for me.

**Comment by jhl13** [comment]
`
pip install wheel
pip install ninja
pip install flash-attn
`
fix my problem.

**Comment by deadpipe** [comment]
> pip install flash-attn --no-build-isolation

Thankyou. It worked

**Comment by hyliu1989** [comment]
The root cause of this issue is the import of torch inside the `setup.py` script. During the fresh installation, there are two Python environments:
1. temporary build-time environment
2. target environment to install fast-attn into

Everything in the import statement of setup.py will be imported from the **build-time environment**. So a solution is to write a pyproject.toml file and specify the build-time dependency. A relatively new pip should recognize pyproject.toml and use it during the installation

Here is an example of the pyproject.toml. Please update the versions of the dependencies to the right one.
```toml
# pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "numpy>=2.2.5,<3.0.0", "torch==2.4.1", "wheel", "ninja"]
build-backend = "setuptools.build_meta"
```

The folder structure is
flash-attention
+ setup.py
+ pyproject.toml
+ (...)

The downside of the approach is, your will install and download the torch package twice, potentially time consuming. The first time is for torch being installed into the build-time environment, the second time, your target environment as a dependency of flash-attention.

**Comment by hyliu1989** [comment]
The ideal way to me is to get rid of import torch in the setup.py.

One potential route is to put a placeholder in flash-attention package, where this placeholder will trigger compilation and installation of the underlying C++ extension at the first execution of your actual ML routine (for example, when you `import flash_attn` the first time in your Jupyter notebook).

**Comment by edsonke** [comment]
I think the error message could be clearer. The check doesn’t only look for PyTorch — it tries to verify several packages, but it just reports 'No module named torch' when one of the checks fails.
From my installation log, it seems like it actually checks these packages:
- torch
- einops
- filelock
- typing-extensions >= 4.10.0
- networkx
- jinja2
- fsspec
- triton == 3.2.0
- setuptools
- sympy == 1.13.1
- mpmath >= 1.1.0, < 1.4
- MarkupSafe >= 2.0
It ends up showing 'No module named torch' if any of these checks fail.
Another way to check for the required packages is to clone the flash-attention repository and try running:
```bash
python setup.py build
```
You can install any missing packages it complains about until it starts building. Once all dependencies are in place, you can stop the build and switch to:
```bash
pip install flash_attn
```

**Comment by p2er1n** [comment]
Hi, I'm here to help those who googled to here.
You can install nvcc first, on Ubuntu, it is `sudo apt install nvidia-cuda-toolkit`
Best wishes to you guys!

**Comment by prhbrt** [comment]
For me torch was found after switching from `uv pip install` on a uv venv, to `pip install`. Probably the uv venv didn't have torch.

I didn't care too much about using uv, since I was just building an apptainer container, but consider checking where torch is located and if that is in the used PYTHON_PATH. (101 python I guess)

**Comment by liugeshy** [comment]
> > try `pip install flash-attn --no-build-isolation` fixed my problem. [pip docs](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation) to fix this problem, maybe adding torch dependency into [pyproject.toml](https://github.com/HazyResearch/flash-attention/blob/main/pyproject.toml) can help
> 
> This worked for me. Thanks ! I actually needed to run those 3 commands :
> 
> ```
> pip install setuptools
> sudo apt-get install python3-dev
> pip install flash-attn==1.0.5 --no-build-isolation
> ```
> 
> I have :
> 
> * Ubuntu 22.04.5 LTS
> * python 3.10.12
> * Cuda compilation tools, release 12.6, V12.6.77
> * torch 2.3.1

thank u ,I have just solved the problem following this

**Comment by Blaubluter** [comment]
wow irgend wie hats geklappt  

nach dem 

pip install wheel
pip install ninja
pip install flash-attn
pip install  packaging
 

 
Successfully built flash-attn
Installing collected packages: einops, flash-attn
Successfully installed einops-0.8.1 flash-attn-2.8.3

**Comment by dipanjanS** [comment]
Can't believe this is still an ongoing problem after over 2 years. 

Same issue on CUDA 12.8 and torch 2.8.0

This is what worked for me in case it helps anyone else

Using 

```
pip install "flash_attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.8cxx11abiTRUE-cp312-cp312-linux_x86_64.whl" 
```

you can replace the version number with any older version also as necessary

**Comment by Anyeos** [comment]
I built flash-attn from source because none of all proposed solutions worked for me. 
You can do:
`gh repo clone Dao-AILab/flash-attention`
then:
`git checkout tags/v2.7.1`
to change version, and next:
`python setup.py install`

The con is you will need to uninstall it manually if you want to update it.

**Comment by heartInsert** [comment]
> Can't believe this is still an ongoing problem after over 2 years.真不敢相信这问题两年多了还在继续。
> 
> Same issue on CUDA 12.8 and torch 2.8.0CUDA 12.8 和 Torch 2.8.0 也有同样的问题
> 
> This is what worked for me in case it helps anyone else这是我用过的方法，如果对其他人有帮助的话
> 
> Using  使用
> 
> ```
> pip install "flash_attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.8cxx11abiTRUE-cp312-cp312-linux_x86_64.whl" 
> ```
> 
> you can replace the version number with any older version also as necessary你也可以根据需要替换任何旧版本

I  swear  you are  the  only  one  God  in github .

**Comment by C0rn3j** [comment]
Had to install using the prebuilt community wheels from https://flashattn.dev/ as I use Python 3.14 for which there are no builds in the release.

**Comment by xvdp** [comment]
Installing flash-attn 2.7.3 to match trellis2 spec, python 3.10,  pytorch 2.6, cuda 12.4 ( installed in conda, on top of native cuda 13 on ubuntu 24.04)
`pip install flash-attn==2.7.3 --no-build-isolation --no-cache-dir` worked for me

**Comment by BossLevel** [comment]
> Can't believe this is still an ongoing problem after over 2 years.
> 
> Same issue on CUDA 12.8 and torch 2.8.0
> 
> This is what worked for me in case it helps anyone else
> 
> Using
> 
> ```
> pip install "flash_attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.8cxx11abiTRUE-cp312-cp312-linux_x86_64.whl" 
> ```
> 
> you can replace the version number with any older version also as necessary

This is the only solution that worked for me - tried all others. Unfortunately this then led to this error: `undefined symbol: _ZN3c104cuda29c10_cuda_check_implementationEiPKcS2_ib` (as I have posted here despite not using vLLM: https://github.com/vllm-project/vllm/issues/36302#issuecomment-4070900635) when attempting to run WAN2.2 (as documented here: https://github.com/Wan-Video/Wan2.2/issues/84)

**Comment by Waliya-noor** [comment]
tried flash-attn version 1.0.5, using python 3.14, torch 2.11.0 and cuda 12.6, however still getting the same issue of `No module named torch` when installing flash-attn. Tried with `--no-build-isolation` as well but same thing

**Comment by JRGit4UE** [comment]
Same 
`ModuleNotFoundError: No module named 'torch'`
problem with 
* Python 3.13.7
* torch 2.11.0 and 
* CUDA 13
