### ISSUE TITLE
Error: Install pip install flash-attn

### ISSUE THREAD

**Issue by toxfu** [HazyResearch/flash-attention#258]
I have the next error:
`
Collecting flash-attn
  Downloading flash_attn-1.0.7.tar.gz (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 8.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\envs\ia\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\anaconda3\envs\ia\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\envs\ia\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fqmch\AppData\Local\Temp\pip-build-env-04mfa98g\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fqmch\AppData\Local\Temp\pip-build-env-04mfa98g\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\fqmch\AppData\Local\Temp\pip-build-env-04mfa98g\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by drx-code** [comment]
Do you solve that problem? It also occurs to me.

**Comment by toxfu** [comment]
no, only that I realized that they had already reported the error as "No Module Named 'torch'" so I closed the issue.

**Comment by prateeky2806** [comment]
did you fix this issue? I am running into a similar issue

**Comment by MattWittbrodt** [comment]
@toxfu @prateeky2806 from another issue I found a workaround: `pip install flash-attn --no-build-isolation`

**Comment by drx-code** [comment]
It solves this problem, thank you.

**Comment by prateeky2806** [comment]
Thanks @MattWittbrodt for the solution. For me using flash-attn==1.0.5 worked.
