### ISSUE TITLE
Support any size of head_size?

### ISSUE THREAD

**Issue by chinoll** [HazyResearch/flash-attention#28]
Hi, Tri Tao,
Can flash-attention support any size of head_size?
Do you have any plans to support other head_size?

**Comment by tridao** [comment]
We support head dimensions 16, 32, 64, 128 (commonly used head dimension in transformers). Since we're using tensor cores, the head dimensions need to be at least divisible by 16.
If there are use cases with other head dimensions, we'd love to understand.

**Comment by nicolas-mng** [comment]
Hi
Can we adjust the `assert` here to allow using head_dim  =128? https://github.com/HazyResearch/flash-attention/blob/6c3a8c65af8c2f2905b60014b4d9cb3d104b90b1/flash_attn/flash_attention.py#L93
Thanks

**Comment by tridao** [comment]
Good catch, thanks!
I've fixed it now.

**Comment by mlw214** [comment]
ViT Huge uses a head dim of 80, could be nice to support that at some point

**Comment by tridao** [comment]
We now support any head dimensions that are multiples of 8, up to 128 (e.g., 8, 16, 24, ..., 128).

**Comment by bhaktatejas922** [comment]
@tridao the new qwen30ba3 vl model gets this error as well, tho it seems all the heads are divisible by 8? 
https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct/blob/main/config.json 

```
6) ERROR 10-15 07:53:38 [core.py:708] EngineCore failed to start.
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708] Traceback (most recent call last):
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 498, in __init__
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 92, in __init__
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     self._initialize_kv_caches(vllm_config)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 190, in _initialize_kv_caches
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     self.model_executor.determine_available_memory())
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 85, in determine_available_memory
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return self.collective_rpc("determine_available_memory")
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return [run_method(self.driver_worker, method, args, kwargs)]
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils/__init__.py", line 3121, in run_method
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return func(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return func(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     self.model_runner.profile_run()
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 3346, in profile_run
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     self.model.get_multimodal_embeddings(
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 1296, in get_multimodal_embeddings
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     vision_embeddings = self._process_image_input(multimodal_input)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 1224, in _process_image_input
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     image_embeds = self.visual(pixel_values,
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]                    ^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return self._call_impl(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return forward_call(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 496, in forward
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     hidden_states = blk(hidden_states,
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]                     ^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return self._call_impl(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return forward_call(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 190, in forward
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     x = x + self.attn(self.norm1(x),
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]             ^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return self._call_impl(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return forward_call(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2_5_vl.py", line 384, in forward
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     output = flash_attn_varlen_func(q,
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]              ^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 233, in flash_attn_varlen_func
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1158, in __call__
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]     return self._op(*args, **(kwargs or {}))
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) ERROR 10-15 07:53:38 [core.py:708] RuntimeError: This flash attention build does not support headdim not being a multiple of 32.
browser-1  | (EngineCore_DP0 pid=546) Traceback (most recent call last):
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
browser-1  | (EngineCore_DP0 pid=546)     self.run()
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
browser-1  | (EngineCore_DP0 pid=546)     self._target(*self._args, **self._kwargs)
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 712, in run_engine_core
browser-1  | (EngineCore_DP0 pid=546)     raise e
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
browser-1  | (EngineCore_DP0 pid=546)     engine_core = EngineCoreProc(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 498, in __init__
browser-1  | (EngineCore_DP0 pid=546)     super().__init__(vllm_config, executor_class, log_stats,
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 92, in __init__
browser-1  | (EngineCore_DP0 pid=546)     self._initialize_kv_caches(vllm_config)
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 190, in _initialize_kv_caches
browser-1  | (EngineCore_DP0 pid=546)     self.model_executor.determine_available_memory())
browser-1  | (EngineCore_DP0 pid=546)     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 85, in determine_available_memory
browser-1  | (EngineCore_DP0 pid=546)     return self.collective_rpc("determine_available_memory")
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
browser-1  | (EngineCore_DP0 pid=546)     return [run_method(self.driver_worker, method, args, kwargs)]
browser-1  | (EngineCore_DP0 pid=546)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/utils/__init__.py", line 3121, in run_method
browser-1  | (EngineCore_DP0 pid=546)     return func(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
browser-1  | (EngineCore_DP0 pid=546)     return func(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
browser-1  | (EngineCore_DP0 pid=546)     self.model_runner.profile_run()
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 3346, in profile_run
browser-1  | (EngineCore_DP0 pid=546)     self.model.get_multimodal_embeddings(
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 1296, in get_multimodal_embeddings
browser-1  | (EngineCore_DP0 pid=546)     vision_embeddings = self._process_image_input(multimodal_input)
browser-1  | (EngineCore_DP0 pid=546)                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 1224, in _process_image_input
browser-1  | (EngineCore_DP0 pid=546)     image_embeds = self.visual(pixel_values,
browser-1  | (EngineCore_DP0 pid=546)                    ^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
browser-1  | (EngineCore_DP0 pid=546)     return self._call_impl(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
browser-1  | (EngineCore_DP0 pid=546)     return forward_call(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 496, in forward
browser-1  | (EngineCore_DP0 pid=546)     hidden_states = blk(hidden_states,
browser-1  | (EngineCore_DP0 pid=546)                     ^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
browser-1  | (EngineCore_DP0 pid=546)     return self._call_impl(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
browser-1  | (EngineCore_DP0 pid=546)     return forward_call(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_vl.py", line 190, in forward
browser-1  | (EngineCore_DP0 pid=546)     x = x + self.attn(self.norm1(x),
browser-1  | (EngineCore_DP0 pid=546)             ^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
browser-1  | (EngineCore_DP0 pid=546)     return self._call_impl(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
browser-1  | (EngineCore_DP0 pid=546)     return forward_call(*args, **kwargs)
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2_5_vl.py", line 384, in forward
browser-1  | (EngineCore_DP0 pid=546)     output = flash_attn_varlen_func(q,
browser-1  | (EngineCore_DP0 pid=546)              ^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 233, in flash_attn_varlen_func
browser-1  | (EngineCore_DP0 pid=546)     out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(
browser-1  | (EngineCore_DP0 pid=546)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546)   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1158, in __call__
browser-1  | (EngineCore_DP0 pid=546)     return self._op(*args, **(kwargs or {}))
browser-1  | (EngineCore_DP0 pid=546)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browser-1  | (EngineCore_DP0 pid=546) RuntimeError: This flash attention build does not support headdim not being a multiple of 32.
```
