### ISSUE TITLE
benchmark_flash_attention.py ERROR

### ISSUE THREAD

**Issue by avatarstones** [HazyResearch/flash-attention#292]
Docker image
nvcr.io/nvidia/pytorch:22.04-py3

GPU:
GPU 0: Tesla P100-PCIE-16GB

Flash attn:

pip install flash-attn --no-build-isolation

Command:
python benchmarks/benchmark_flash_attention.py

Got error:

FlashAttention - Forward pass
Traceback (most recent call last):
  File "benchmarks/benchmark_flash_attention.py", line 68, in <module>
    benchmark_all(fn, qkv_unpad, repeats=repeats, desc='FlashAttention')
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/utils/benchmark.py", line 89, in benchmark_all
    benchmark_forward(fn, *inputs, repeats=repeats, desc=desc, verbose=verbose,
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/utils/benchmark.py", line 17, in benchmark_forward
    fn_amp(*inputs, **kwinputs)
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/utils/benchmark.py", line 15, in fn_amp
    fn(*inputs, **kwinputs)
  File "benchmarks/benchmark_flash_attention.py", line 65, in <lambda>
    fn = lambda qkv_unpad: flash_attn_unpadded_qkvpacked_func(
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py", line 256, in flash_attn_unpadded_qkvpacked_func
    return FlashAttnQKVPackedFunc.apply(qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale,
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py", line 58, in forward
    out, softmax_lse, rng_state, S_dmask = _flash_attn_forward(
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py", line 21, in _flash_attn_forward
    softmax_lse, rng_state, *rest = flash_attn_cuda.fwd(
RuntimeError: Expected is_sm90 || is_sm8x || is_sm75 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

Could you please help me?

**Comment by tridao** [comment]
FlashAttention doesn't run on P100, only Turing (sm75), Ampere (sm80, 86, 89) and Hopper (sm90) are supported.
