### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by NoOneUST** [HazyResearch/flash-attention#300]
command:  gcc --version
    gcc (GCC) 10.1.0
    Copyright (C) 2020 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    command: nvcc -V
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2020 NVIDIA Corporation
    Built on Tue_Sep_15_19:10:02_PDT_2020
    Cuda compilation tools, release 11.1, V11.1.74
    Build cuda_11.1.TC455_06.29069683_0
    
    command: python -c "import torch; import torch.utils; import torch.utils.cpp_extension;  
    print(torch.utils.cpp_extension.CUDA_HOME)"
    /mine/cuda-11.1

     command: pip install flash_attn==1.0.5 --no-cache-dir
      ptxas info    : Function properties for _Z40fmha_bwd_q_dk_dv_loop_seqparallel_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb0EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 181 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z40fmha_bwd_q_dk_dv_loop_seqparallel_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z40fmha_bwd_q_dk_dv_loop_seqparallel_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 183 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb0ELi2EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb0ELi2EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 199 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1ELi2EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1ELi2EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 216 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb0ELi1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb0ELi1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 195 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1ELi1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1ELi1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 195 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb0ELin1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb0ELin1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 246 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1ELin1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb0ELb1ELin1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 222 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z24fmha_bwd_dot_do_o_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z24fmha_bwd_dot_do_o_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 29 registers, 640 bytes cmem[0]
      ptxas info    : Compiling entry function '_Z40fmha_bwd_q_dk_dv_loop_seqparallel_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z40fmha_bwd_q_dk_dv_loop_seqparallel_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 185 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z40fmha_bwd_q_dk_dv_loop_seqparallel_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z40fmha_bwd_q_dk_dv_loop_seqparallel_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 193 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0ELi2EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0ELi2EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 203 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1ELi2EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1ELi2EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 207 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0ELi1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0ELi1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 199 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1ELi1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1ELi1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 200 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0ELin1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb0ELin1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 226 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ptxas info    : Compiling entry function '_Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1ELin1EEv17FMHA_dgrad_params' for 'sm_80'
      ptxas info    : Function properties for _Z29fmha_bwd_dq_dk_dv_loop_kernelI18FMHA_kernel_traitsILi128ELi64ELi16ELi1ELi8ELj8E13__nv_bfloat16ELb1ELb1ELin1EEv17FMHA_dgrad_params
          0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
      ptxas info    : Used 228 registers, 640 bytes cmem[0], 16 bytes cmem[2]
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/mine/anaconda3/envs/bevfusion/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/mine/anaconda3/envs/bevfusion/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/mine/anaconda3/envs/bevfusion/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mine/anaconda3/envs/bevfusion/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 163, in <module>
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/tmp/pip-build-env-_rvjl4_q/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for flash_attn
      Failed to build flash_attn
      ERROR: Could not build wheels for flash_attn, which is required to install pyproject.toml-based projects

**Comment by tridao** [comment]
As mentioned in the README, we need CUDA >= 11.4 for FlashAttention.

**Comment by timmoon10** [comment]
I think there's something beyond CUDA versioning. I see the same error with CUDA 12.1 ([NGC container 23.03](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)). See https://github.com/NVIDIA/TransformerEngine/actions/runs/5489940835/jobs/10004731952?pr=302.

**Comment by tridao** [comment]
@timmoon10 I think these could be different issues. 
I routinely compile on the NGC containers and that has always worked.
I looked at the log of the TE build and couldn't see what exactly the error was, I could only see warnings.

**Comment by timmoon10** [comment]
The lack of error messages does make things tricky. FlashAttention builds successfully on my own system, so my hypothesis is an OOM error on underpowered systems like the GitHub runners. I know PyTorch exposes the [`MAX_JOBS` environment variable](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.BuildExtension) to prevent excessive parallel Ninja jobs from blowing up the system. There aren't great solutions if the OOM happens in the linker though, aside from reducing the size of the library and reducing the number of compiled kernels.

@NoOneUST What kind of system have you been building on?

**Comment by timmoon10** [comment]
I confirm that my error is an OOM that happens when building Flash Attention, but I don't think Flash Attention is the root cause. Building Flash Attention without TE seems to work fine: https://github.com/NVIDIA/TransformerEngine/actions/runs/5513261506/jobs/10051156004?pr=314

**Comment by NoOneUST** [comment]
> The lack of error messages does make things tricky. FlashAttention builds successfully on my own system, so my current hypothesis is an OOM error on underpowered systems like the GitHub runners. I know PyTorch exposes the [`MAX_JOBS` environment variable](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.BuildExtension) to prevent excessive parallel Ninja jobs from blowing up the system. There aren't great solutions if the OOM happens in the linker though, aside from reducing the size of the library and reducing the number of compiled kernels.
> 
> @NoOneUST What kind of system have you been building on?

Thank you for your reply. Here is my system information:

```
(command) cat /etc/redhat-release: 
AlmaLinux release 9.2 (Turquoise Kodkod)

Memory: 15.9 GB /1.47 TB
Swap: 0/128 GB

CPU: Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz (20 Core 40 Threads)

GPU: 8x 24G RTX 3090
```

**Comment by NoOneUST** [comment]
> 

How should we install Flash Attention without TE?

**Comment by tridao** [comment]
@NoOneUST We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

**Comment by timmoon10** [comment]
For the record, Transformer Engine is not causing @NoOneUST's error. We just get failures in the same place. It seems compiling the Flash Attention CUDA kernels is an intensive process, so it can expose other system errors. In the case of TE, we were already close to the system memory limit and Flash Attention pushed us over. This doesn't seem to be the case for @NoOneUST given his system specs.

**Comment by xiaohangguo** [comment]
How long does it usually take to compile, I'm still compiling after over an hour

**Comment by tridao** [comment]
We have prebuilt wheels that setup.py should automatically download (e.g. https://github.com/Dao-AILab/flash-attention/releases/tag/v2.1.1).
