### ISSUE TITLE
support for FlashBlocksparseMHA

### ISSUE THREAD

**Issue by cmlakhan** [HazyResearch/flash-attention#31]
I am trying to run a transformer model with very long sequence length so I was thinking of using FlashBlocksparseMHA but it seems I should set sparsity_config

Could you explain what I need to set within the 'sparsity_config' in order to get it to work?  I don't see any instructions on the GitHub repo

**Comment by cmlakhan** [comment]
Looking at some of your other code it seems you need to instantiate ```SparsityConfig``` class

so I did the following for my transformer block
```
from deepspeed.ops.sparse_attention import SparsityConfig
class TransformerBlock(nn.Module):
    def __init__(self,
                 dropout,
                 d_model,
                 n_transformer_heads,
                 positional_encoding=False, **kwargs):
        super(TransformerBlock, self).__init__(**kwargs)
        if positional_encoding:
            use_rotary_emb = '1d'
        else:
            use_rotary_emb = None
        sparse_config = SparsityConfig(num_heads = n_transformer_heads,
                                        block = 32768)
        self.flash_mha = FlashBlocksparseMHA(embed_dim = d_model,
                                             sparsity_config = sparse_config,
                                             num_heads = n_transformer_heads,
                                             attention_dropout = dropout,
                                             use_rotary_emb = use_rotary_emb)
        self.ffn = PositionWiseFFN(d_model, d_model, d_model)
        self.addnorm1 = AddNorm(d_model, dropout)
        self.addnorm2 = AddNorm(d_model, dropout)
    def forward(self, x):
        x_mha, attention_weights = self.flash_mha(x, x, x)
        x = self.addnorm1(x, x_mha)
        return self.addnorm2(x, self.ffn(x))



```

but when I instantiate it then I get the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 20, in __init__
  File "<stdin>", line 12, in __init__
  File "<stdin>", line 14, in __init__
  File "/hpc/users/lakhac01/flash-attention/flash_attn/flash_blocksparse_attention.py", line 124, in __init__
    self.inner_attn = FlashBlocksparseAttention(
  File "/hpc/users/lakhac01/flash-attention/flash_attn/flash_blocksparse_attention.py", line 27, in __init__
    self.sparsity_config = hydra.utils.instantiate(sparsity_config)
  File "/sc/arion/projects/ad-omics/clakhani/conda/envs/flash_attention_lightning/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate
    raise InstantiationException(
hydra.errors.InstantiationException: Cannot instantiate config of type SparsityConfig.
Top level config must be an OmegaConf DictConfig/ListConfig object,
a plain dict/list, or a Structured Config class or instance.


```


I can't figure out if this is just a formatting issue or I need to used a specialized sparseconfig class

**Comment by tridao** [comment]
A sparsity config is one that generates the block sparsity mask (i.e., [layout](https://github.com/HazyResearch/flash-attention/blob/6cc7342575393568f32c69aba6365e93d7701cbb/flash_attn/flash_blocksparse_attention.py#L33)) for a given sequence length, where each block has shape 16 x 256. 

The instantiation with hydra is a little hard to use, you can get rid of it.

I'll add an example sparsity_config soon.

**Comment by cmlakhan** [comment]
That would be great to see an example, thank you!  It sounds like you have a specific mask in mind for this architecture.  From the text in your paper I guess you are saying $B_r$ = 16 and $B_c$ = 256?  I'm trying to train a BERT-like DNA sequence model with max length 131072 so I'm trying to figure out whether the sparsity mask you are suggesting would still allow me to attend to all elements of the input sequence.  Some masks such as the Open AI Sparse Transformer have a mix of local blocks and global blocks which seem to allow that but I wasn't clear about your sparse block masking scheme.

<img width="677" alt="Screen Shot 2022-08-08 at 1 31 29 PM" src="https://user-images.githubusercontent.com/2146422/183479736-c5f0dec5-d5b2-4c03-b64c-ae85d3818404.png">



<img width="695" alt="Screen Shot 2022-08-08 at 1 38 17 PM" src="https://user-images.githubusercontent.com/2146422/183479682-c01c8441-0e46-41ef-8182-9c837c3de741.png">

**Comment by tridao** [comment]
Any sparsity mask would work as long as `B_r = 16` and `B_c = 256` (that's what we have implemented).

**Comment by sophiawisdom** [comment]
Did you end up adding an example sparsity_config? I'm running in to the same problem. I'd be happy to remove the Hydra instantiation if you would be OK with that.

**Comment by nofreewill42** [comment]
I also would like to use the FlashBlocksparseAttention module but I cannot make it work after a few hours of trying.
 @tridao can you please shed some light on this?
