### ISSUE TITLE
assertion error " assert qkv.dtype == torch.float16"

### ISSUE THREAD

**Issue by cmlakhan** [HazyResearch/flash-attention#9]
I wanted to test out your flashattention implemention for a problem that I have been working out.  I tried to create a simple single layer attention module but I am getting an assertion layer error.  This is my module

```
class multiple_heads_attention(nn.Module):
    def __init__(self, model_params):
        super().__init__()
        self.num_bins = model_params['num_bins']
        self.bin_width = model_params['bin_width']
        self.d_model = model_params['d_model']
        self.n_transformer_heads = model_params['n_transformer_heads']
        self.num_outputs = model_params['num_outputs']
        self.input_dim = 4
        self.token_emb = nn.Linear(self.input_dim, self.d_model, bias=False)
        self.max_seq_len = context_length
        #self.pos_emb = nn.Embedding(self.max_seq_len, self.d_model)
        self.linear = nn.Linear(self.d_model, self.num_outputs)
        self.m_pos = nn.Softplus()
        self.flash_mha_1 = FlashMHA(self.d_model,
                                    num_heads = model_params['n_transformer_heads'],
                                    attention_dropout = .1,
                                    use_rotary_emb = '1d')
    def forward(self, x, **kwargs):
        x = x.transpose(1, 2)
        x = self.token_emb(x)
        x = self.flash_mha_1(x,x,x)
        return x
```

but I get an error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sc/arion/projects/ad-omics/clakhani/conda/envs/flash_attention_lightning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<stdin>", line 27, in forward
  File "/sc/arion/projects/ad-omics/clakhani/conda/envs/flash_attention_lightning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/hpc/users/lakhac01/flash-attention/flash_attn/flash_attention.py", line 112, in forward
    context, attn_weights = self.inner_attn(qkv, key_padding_mask=key_padding_mask,
  File "/sc/arion/projects/ad-omics/clakhani/conda/envs/flash_attention_lightning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/hpc/users/lakhac01/flash-attention/flash_attn/flash_attention.py", line 41, in forward
    assert qkv.dtype == torch.float16
AssertionError
```

I'm guessing I need to cast my vectors as torch.float16?  If I do that then it causes an error with my linear embedding layer.  I'm trying to understand what to do in this case.  Also, what is the purpose of the arguments "x_ignored_, x_ignored_1_" in the forward pass?  I just put x back into the model because I'm not sure what else I should do.

**Comment by tridao** [comment]
Yes, we currently support fp16 only. You can run your model with torch AMP (https://pytorch.org/docs/stable/amp.html).

The arguments "x_ignored_, x_ignored_1_" are completely ignored, this was because we were at some point trying to maintain the same interface as Pytorch MHA (https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html).
But I see that it's confusing, so I'll redo the interface soon.

**Comment by cmlakhan** [comment]
Thanks for letting me know!  Have you tried this with PyTorch lightning?  I am guessing I just need to set the precision flag to 16?

For the time being I'm guessing this is the right way to use forward?

```
x = self.flash_mha_1(x,x,x)

```

**Comment by tridao** [comment]
Yes, we've been training models with Pytorch lightning, setting precision to 16.
Yes, that the right way.

**Comment by cmlakhan** [comment]
Great, thank you
